export enum postTypes {
    FETCH_POST_REQUEST = "FETCH_POST_REQUEST",
    FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS",
    FETCH_POST_FAILURE = "FETCH_POST_FAILURE",


    DELETE_POST_REQUEST = "DELETE_POST_REQUEST",
    DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS",
    DELETE_POST_FAILURE = "DELETE_POST_FAILURE",


    EDIT_POST_REQUEST = "EDIT_POST_REQUEST",
    EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS",
    EDIT_POST_FAILURE = "EDIT_POST_FAILURE",

    ADD_POST_REQUEST = "ADD_POST_REQUEST",
    ADD_POST_SUCCESS = "ADD_POST_SUCCESS",
    ADD_POST_FAILURE = "ADD_POST_FAILURE"
}
